### ISSUE TITLE
Can't run Linux Commands on Windows Machine,  Any tips or Advice ??

### ISSUE THREAD

**Issue by Yash-verma18** [kunal-kushwaha/DevOps-Bootcamp#19]
I used Hyper terminal too, Most commands worked on it, But commands like "chmod" are not working. Even windows default terminal wasn't working.  Any solutions are highly welcome.

**Comment by Saurabhpatil-dev** [comment]
@Yash-verma18 Try this https://cmder.net/   .  It is an emulator.

**Comment by Yash-verma18** [comment]
@Saurabhpatil-dev  Thanks !! It Certainly Helps.
