### ISSUE TITLE
I'm unable to access the devops tools playlist as it says Playlist does not exist.

### ISSUE THREAD

**Issue by ZecTox** [kunal-kushwaha/DevOps-Bootcamp#82]

**Comment by iminoaru** [comment]
seems like the playlist of tools in removed or merged with the complete playlist.
I will create a pull request to remove that link.

**Comment by Debaditya-Som** [comment]
I have resolved the issue and have given a pull request. 
Hope it gets merges soon.

**Comment by iminoaru** [comment]
Looks like the repo is not being maintained, my pull request from May is not merged/reviewed yet.

**Comment by Debaditya-Som** [comment]
Maybe it is not maintained, hopefully it will get merged someday.
