### ISSUE TITLE
Networking Devices PDF missing

### ISSUE THREAD

**Issue by Susmita-Dey** [kunal-kushwaha/DevOps-Bootcamp#9]
In the Networking video at timestamp 1:39:52 Networking Devices (Download PDF), the pdf is missing here. Kindly upload it here.

**Comment by priyansh2998** [comment]
for some reason it's not loading but file is there , try downloading u will be able to see the file

**Comment by Yash-verma18** [comment]
I think You can check on google, For the same.  I did the same thing.

**Comment by Harsh21ranjan** [comment]
Just make your own notes

**Comment by Susmita-Dey** [comment]
> I think You can check on google, For the same. I did the same thing.

Kunal had made the timestamps as Download PDF of the Networking Devices. So, I though it would here as notes. But it's not here. I haven taken some screenshots at that time but all was not visible properly due to Kunal's face as some parts of a topic gone behind. It was itself a PDF file. So it would have been better if @kunal-kushwaha added it here.

**Comment by ritikranjan12** [comment]
@kunal-kushwaha  @Susmita-Dey @Harsh21ranjan I had added Pull request #13 for the Networking Device pdf.
